{% set version = "3.10.2" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: aedb48010ebfab9651aaab1df5fd3b4848eb4182afc909852a2110c24f89a359

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

about:
  home: http://www.django-rest-framework.org
  license: BSD-2-Clause
  license_file: LICENSE.md
  summary: 'Web APIs for Django, made easy'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
