{% set version = "3.10.0" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: 1f274ebbb930dfa709751fac31b2332b2e662303f8c66d7eacea534702611e34

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

about:
  home: http://www.django-rest-framework.org
  license: BSD 2-Clause
  summary: 'Web APIs for Django, made easy'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
