{% set version = "3.9.1" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: 79c6efbb2514bc50cf25906d7c0a5cfead714c7af667ff4bd110312cd380ae66

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

about:
  home: http://www.django-rest-framework.org
  license: BSD 2-Clause
  summary: 'Web APIs for Django, made easy'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
