{% set version = "3.12.0" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: 9d5b07a2dd29b4fb18da2e6a888051f34b286b3bfc1c3fe885a17e16e389c569

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

about:
  home: http://www.django-rest-framework.org
  license: BSD-2-Clause
  license_file: LICENSE.md
  summary: Web APIs for Django, made easy

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
