{% set version = "3.13.1" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: 0c33407ce23acc68eca2a6e46424b008c9c02eceb8cf18581921d0092bc1f2ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=2.2

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.django-rest-framework.org
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Web APIs for Django, made easy

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
