{% set version = "3.7.0" %}

package:
  name: djangorestframework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework/djangorestframework-{{ version }}.tar.gz
  sha256: 8ba4908d9fe4d78a8459fe86922e434006d491d4486086d23b19cd0975a3dba5

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - rest_framework
    - rest_framework.authtoken
    - rest_framework.authtoken.migrations
    - rest_framework.templatetags
    - rest_framework.utils

about:
  home: http://www.django-rest-framework.org
  license: BSD 2-Clause
  summary: 'Web APIs for Django, made easy'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
