travis:
  secure:
    BINSTAR_TOKEN: MeuQs/VQqbk/+25NzUqPJI7D9bALJUzWRrlt8HNSdrQ27IkDMjd2Rmt9Cn1WQPpompi2iJgDIB8I21YjFR9EqJCO3uouFoiVlvDk5m8ag1BPzW8iDqMziWb9jlDrSnFlh8rIcqu4LbXRtD3tQjgt511anVJ7o4Gy9b+cpZgI+K6vmoa6q8HV3jhPgVeqF/BRU5ReDX+6Xy0ypL68++Y0Cf9pFuMZ70p8P+bl5fUKwPOd4pnttfMJJfyVekGATOS5TdWhtvy+WEJ9OL/4HxaRBOjX+2MmZn54h3PyQx/gsutUiwESrlInoExiFwTie94vNHRG+iiJRJb9vSrRWT/rPhPRwZgR2YyLT1VjOaHew11OPJFm6+Y3BiuOkcAg5Dh4udKrZmSPH2yM7DvtE2v4NFgeZrRovanCwY8t9zC6FjOlu3kJ/1H+uHRWg50zS70WPCqx/XJaXCiyrmDsblLWlHjPYXMg6FSyAgwxKCZ+g3iUGmjga2JbQmJN3fb9/KRHN7AKPEii+T58PvFd6mUXUfqqGES6DefqBt3WZzN8rYDbh8wuR27CqhTatGrDF53nh3XhLA/otQD4lt77lbun9o/IwUOjm6Ub+eN5K2KjpMhPmDY5AZCfvY5/3DLyiVT81FC/LPBLxk8EY6gSHX94w8Q+tN6GOfApK1zDkkKR0rI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
