travis:
  secure:
    BINSTAR_TOKEN: lS/IdP9b8aTEwztWKqBR56ITG1xBsXpbST0/HOsTLK7QCw49RtOa7DIINCAHPBFxDpo5r2k6Z3O1vORqSo/rO/pn9F60apKeIJZItnCuJtByJxhxl5BdU4QOUg3vbGGfWeXfTckJ08i+BgXfN10LrPZ5ruPQywCBk6YTNT4MC+mbHFSmHf9bwM8rGx1S7epZSMLgzRNXzfwMvFJN3qQFunz8YP1AH2ZoPcxIsjzN/rcjIKvXX8QT9YKLU0xinP8BccCwG7RFwF4MvTW8WaJUF7EifCP44pB/HPLcTQfkc3lddLCRFvdp2ruloyd/81WhPx72WoxsIXh3Ymvi8y/DPPCiD93bBpv1oUnUay/ENU/SHbbopWTcBdYD31yb4k44WIc1BT1o/ODAoCGG9kOAZJuBM1PLDy7OTNeOageumnBYHTAsW1AubAYl3IzxUTzsg8CMXIHNgSo6kPaLOrRkGE5ihuUPXPAh9WjUBk3B2os9WXuRx9/sIqcwifVprY6DJfYKcsPGMPrJF+ZiVL5SPceDyHWCrFjVKgiYaIJl5Oz5YByxtuNZMBgxBv9mj9MOANsLDmBMwi6bzNu7QD3Pxxm1BNOhPR+MMMU3QD9Cwl4Do8KvnSh0kVknqgz74w87TcrxJzcCnTBHmWYPErp02lrV3hLCOpS2FqRfUT2CL1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
